1. Importing Necessary Libraries

In [15]:
import pandas as pd

In [16]:
df=pd.read_json("PL_Table.json",lines=True)

In [17]:
df.head()

       sku                 PL
0  0X749QB   DELL0X_PC_Laptop
1  75X62BB  DELL75_PC_Monitor
2   DF627B     DELLDF_SUP_TON
3   4ZB96A         HP4Z_PH_LJ
4  0R0N0QB   DELL0R_PC_Laptop

In [18]:
def extracting_category_subcategory(pl_value):
    parts = pl_value.split("_")

    if len(parts) >= 3:
        category = parts[1]
        subcategory = parts[2]
    else:
        category = None
        subcategory = None

    return pd.Series([category, subcategory])

In [19]:
df[["category","subcategory"]] = df["PL"].apply(extracting_category_subcategory)

In [20]:
df.head()

       sku                 PL category subcategory
0  0X749QB   DELL0X_PC_Laptop       PC      Laptop
1  75X62BB  DELL75_PC_Monitor       PC     Monitor
2   DF627B     DELLDF_SUP_TON      SUP         TON
3   4ZB96A         HP4Z_PH_LJ       PH          LJ
4  0R0N0QB   DELL0R_PC_Laptop       PC      Laptop

In [21]:
df.sku.count()

np.int64(1598)

In [22]:
df.category.value_counts()

category
SUP    780
PC     640
PH     178
Name: count, dtype: int64

In [23]:
df.subcategory.value_counts()

subcategory
INK        426
Laptop     416
TON        326
Desktop    164
IJ          84
LJ          74
Monitor     60
UNK         28
SJ          20
Name: count, dtype: int64

In [24]:
Category_mapping_table_cleaned = df[["sku","PL","category","subcategory"]]

In [25]:
Category_mapping_table_cleaned.to_csv("Category_mapping_Table_Cleaned.csv", index=False)