In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('category_mapping_Table_Cleaned.csv')

In [4]:
df.head()

       sku                 PL category subcategory
0  0X749QB   DELL0X_PC_Laptop       PC      Laptop
1  75X62BB  DELL75_PC_Monitor       PC     Monitor
2   DF627B     DELLDF_SUP_TON      SUP         TON
3   4ZB96A         HP4Z_PH_LJ       PH          LJ
4  0R0N0QB   DELL0R_PC_Laptop       PC      Laptop

In [7]:
df.drop(columns="category", inplace=True)

In [10]:
df.head()

       sku                 PL subcategory
0  0X749QB   DELL0X_PC_Laptop      Laptop
1  75X62BB  DELL75_PC_Monitor     Monitor
2   DF627B     DELLDF_SUP_TON         TON
3   4ZB96A         HP4Z_PH_LJ          LJ
4  0R0N0QB   DELL0R_PC_Laptop      Laptop

In [11]:
PL_table_cleaned=df[["sku","PL","subcategory"]]

In [12]:
PL_table_cleaned.to_csv("PL_Table_Cleaned.csv", index=False)